---
- name: Ensure to add Ubuntu Universe repo for required packages
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://in.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main universe"
    - "deb http://in.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main universe"
    - "deb http://in.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main universe"
    - "deb http://in.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main universe"
  when: ansible_distribution == "Ubuntu"

- name: Install required packages for selected NetBox configuration
  apt:
    name: "{{ item }}"
    state: latest
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - "{{ netbox_python_packages }}"
    - "{{ netbox_packages }}"
    - "{{ netbox_ldap_packages if netbox_ldap_enabled else [] }}"
    - "{{ 'git' if netbox_git else [] }}"
    - "{{ 'acl' if ('SUDO_USER' in ansible_env and ansible_env.SUDO_USER != 'root') else [] }}"
